{{- if .Values.rbac.create -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "octops-fleet-gs.serviceAccountName" . }}
  labels:
    {{- include "octops-fleet-gs.labels" . | nindent 4 }}
rules:
  - apiGroups: ["agones.dev"]
    resources: ["gameservers", "fleets"]
    verbs: ["get", "update", "delete", "list", "watch"]
  - apiGroups: [ "autoscaling.agones.dev" ]
    resources: [ "fleetautoscalers"]
    verbs: [ "get", "update", "list", "watch" ]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "octops-fleet-gs.serviceAccountName" . }}
  labels:
    {{- include "octops-fleet-gs.labels" . | nindent 4 }}
subjects:
  - kind: User
    name: "system:serviceaccount:octops-system:{{ include "octops-fleet-gs.serviceAccountName" . }}"
    apiGroup: rbac.authorization.k8s.io
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "octops-fleet-gs.serviceAccountName" . }}
{{- end }}